<a href="https://colab.research.google.com/github/akshatsinha0407/PythonColab/blob/main/Pytorch1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
print(torch.__version__)

2.9.0+cu126


In [2]:
if torch.cuda.is_available():
    device = torch.device("cuda")
    print(torch.cuda.get_device_name(0))
else :
    device = torch.device("cpu")
print(device)

Tesla T4
cuda


In [3]:
torch.empty(2,3)

tensor([[4.0640e-40, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 1.4013e-45, 0.0000e+00]])

In [5]:
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [9]:
torch.rand(2,3)

tensor([[0.5939, 0.0225, 0.5212],
        [0.7489, 0.4089, 0.6332]])

In [15]:
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [19]:
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [25]:
print("using range", torch.arange(0,10,2))


print("using linspace",torch.linspace(0,10,5))


print("using eye",torch.eye(3))


print("using empty",torch.full((2,3),5))


using range tensor([0, 2, 4, 6, 8])
using linspace tensor([ 0.0000,  2.5000,  5.0000,  7.5000, 10.0000])
using eye tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])
using empty tensor([[5, 5, 5],
        [5, 5, 5]])


In [27]:
x = torch.tensor([[1,2,3],[4,5,6]])
x.shape

torch.Size([2, 3])

In [29]:
torch.empty_like(x)

tensor([[2308668953601599342, 8242558622326857760, 2322289982652575849],
        [2314885530454750323, 7305508525132750880, 7526676553110265964]])

In [30]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [31]:
torch.tensor([1.0,2.0,3.0], dtype=torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [32]:
torch.tensor([1,2,3], dtype=torch.float64)

tensor([1., 2., 3.], dtype=torch.float64)